### ISSUE TITLE
Wrap labels to prevent window from resizing

### ISSUE THREAD

**Issue by cassidyjames** [linuxhubit/gitscover#6]
Some labels can get really long, like the tags and description. Right now the window just resizes which can get mildly annoying:

![Screenshot from 2020-11-06 12 36 54](https://user-images.githubusercontent.com/611168/98407444-ee15fb80-202c-11eb-89ab-4d99e679a416.png)

or reaaaally bad:

![Screenshot from 2020-11-06 12-37-36](https://user-images.githubusercontent.com/611168/98407455-f4a47300-202c-11eb-9d8c-743abfa5e53a.png)

**Comment by mirkobrombin** [comment]
This can actually be a problem :D
